# Generated by Django 3.2.13 on 2022-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
